<Project>
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<MasaFrameworkPackageVersion>1.2.0-preview.*</MasaFrameworkPackageVersion>
		<MasaStackSdksPackageVersion>1.2.1-preview.*</MasaStackSdksPackageVersion>
		<MicrosoftPackageVersion>6.*</MicrosoftPackageVersion>
	</PropertyGroup>
</Project>
