global using Masa.Contrib.Service.Caller.HttpClient;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using Masa.BuildingBlocks.Service.Caller;
global using Masa.Alert.ApiGateways.Caller.Base;
global using Masa.Alert.ApiGateways.Caller.Const;
global using Masa.Alert.Application.Contracts.AlarmRules.Dtos;
global using Masa.Alert.Infrastructure.Ddd.Application.Contracts.Dtos;
global using Masa.Alert.ApiGateways.Caller.Services.AlarmRules;
global using Masa.Alert.Application.Contracts.AlarmHistories.Dtos;
global using Masa.Alert.ApiGateways.Caller.Services.AlarmHistories;
global using Masa.Alert.Application.Contracts.WebHooks.Dtos;
global using Masa.Alert.ApiGateways.Caller.Services.WebHooks;
global using Microsoft.Extensions.Logging;
global using Masa.Contrib.StackSdks.Caller;
global using System.Net;
global using AuthenticationService = Masa.Contrib.StackSdks.Caller.AuthenticationService;
global using Masa.BuildingBlocks.Isolation;