<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Masa.Alert.Application.Contracts\Masa.Alert.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Masa.Alert.Infrastructure.Ddd.Application.Contracts\Masa.Alert.Infrastructure.Ddd.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
