// Copyright (c) MASA Stack All rights reserved.
// Licensed under the Apache License. See LICENSE.txt in the project root for license information.

global using System.Collections.Concurrent;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using FluentValidation;
global using Mapster;
global using Masa.Alert.ApiGateways.Caller;
global using Masa.Alert.ApiGateways.Caller.Services.AlarmHistories;
global using Masa.Alert.ApiGateways.Caller.Services.AlarmRules;
global using Masa.Alert.ApiGateways.Caller.Services.WebHooks;
global using Masa.Alert.Application.Contracts.AlarmHistories.Dtos;
global using Masa.Alert.Application.Contracts.AlarmRules.Dtos;
global using Masa.Alert.Application.Contracts.QueryModels;
global using Masa.Alert.Application.Contracts.WebHooks.Dtos;
global using Masa.Alert.Domain.Shared.AlarmHistory;
global using Masa.Alert.Domain.Shared.AlarmRules;
global using Masa.Alert.Domain.Shared.Enums;
global using Masa.Alert.Infrastructure.Common.Extensions;
global using Masa.Alert.Infrastructure.Common.Utils;
global using Masa.Alert.Infrastructure.Ddd.Application.Contracts.Dtos;
global using Masa.Alert.Web.Admin.Components;
global using Masa.Alert.Web.Admin.Components.Modules.Alarm;
global using Masa.Alert.Web.Admin.Global;
global using Masa.Alert.Web.Admin.Pages.AlarmHistory.Modules;
global using Masa.Alert.Web.Admin.Pages.AlarmRules.Modules;
global using Masa.Alert.Web.Admin.Pages.WebHooks.Modules;
global using Masa.Alert.Web.Admin.ViewModel.AlarmHistory;
global using Masa.Alert.Web.Admin.ViewModel.AlarmRules;
global using Masa.Alert.Web.Admin.ViewModel.WebHooks;
global using Masa.Blazor;
global using Masa.BuildingBlocks.StackSdks.Auth;
global using Masa.BuildingBlocks.StackSdks.Auth.Contracts.Model;
global using Masa.BuildingBlocks.StackSdks.Mc.Enum;
global using Masa.BuildingBlocks.StackSdks.Pm;
global using Masa.BuildingBlocks.StackSdks.Pm.Model;
global using Masa.BuildingBlocks.StackSdks.Tsc;
global using Masa.BuildingBlocks.StackSdks.Tsc.Contracts.Model;
global using Masa.BuildingBlocks.StackSdks.Tsc.Model;
global using Masa.Contrib.StackSdks.Caller;
global using Masa.Stack.Components;
global using Masa.Stack.Components.Extensions;
global using Masa.Stack.Components.Models;
global using Masa.Stack.Components.TaskHandle;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Rendering;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.Extensions.DependencyInjection;
global using ProjectModel = Masa.BuildingBlocks.StackSdks.Pm.Model.ProjectModel;
global using MasaGlobalConfig = Masa.Stack.Components.Configs.GlobalConfig;